# Generated by Django 4.1.2 on 2022-10-17 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cnab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.CharField(max_length=10)),
                ("cpf", models.CharField(max_length=10)),
                ("card", models.CharField(max_length=12)),
                ("hour", models.DateTimeField()),
                ("owner", models.CharField(max_length=14)),
                ("store_name", models.CharField(max_length=19)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cnab",
                        to="transactions.transaction",
                    ),
                ),
            ],
        ),
    ]
