# Generated by Django 4.1.2 on 2022-11-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cnab", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cnab",
            name="hour",
            field=models.TimeField(),
        ),
    ]
