# Generated by Django 4.1.2 on 2022-11-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_transaction_transaction_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.CharField(
                choices=[
                    ("Débito", "Debito"),
                    ("Boleto", "Boleto"),
                    ("Financiamento", "Financiamento"),
                    ("Crédito", "Credito"),
                    ("Recebimento Empréstimo", "Recebimento Emprestimo"),
                    ("Vendas", "Vendas"),
                    ("Recebimento TED", "Recebimento Ted"),
                    ("Recebimento DOC", "Recebimento Doc"),
                    ("Aluguel", "Aluguel"),
                ],
                max_length=25,
                unique=True,
            ),
        ),
    ]
